version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://docuguardian:docuguardian123@postgres:5432/docuguardian
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: >
      sh -c "python -c 'from app.db.init_db import init_db; init_db()' &&
             python create_admin.py &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: docuguardian
      POSTGRES_PASSWORD: docuguardian123
      POSTGRES_DB: docuguardian
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 